version: "3"
networks:
  app-tier:
    driver: bridge

services:
  mysql_server:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    networks:
      - app-tier
    environment:
      MYSQL_DATABASE: app_v1
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
      MYSQL_ROOT_PASSWORD: password@12345
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser
      MYSQL_ROOT_HOST: '%'
    container_name: db_container_flask

  api:
    build: ./src
    container_name: api_container_flask
    ports:
      - '5000:5000'
    expose:
      - "5000"
    networks:
      - app-tier
    volumes:
      - ./src:/app
    depends_on:
      - mysql_server
