"""empty message

Revision ID: 8d95909745e1
Revises: da76889001cd
Create Date: 2022-09-21 20:26:26.264828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d95909745e1'
down_revision = 'da76889001cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('unique_access', sa.String(length=300), nullable=True))
    op.create_unique_constraint(None, 'companies', ['unique_access'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_column('companies', 'unique_access')
    # ### end Alembic commands ###
