"""empty message

Revision ID: 9678ac6a1bc3
Revises: 8d95909745e1
Create Date: 2022-09-21 20:27:53.882873

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9678ac6a1bc3'
down_revision = '8d95909745e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'unique_access',
               existing_type=mysql.VARCHAR(length=300),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'unique_access',
               existing_type=mysql.VARCHAR(length=300),
               nullable=True)
    # ### end Alembic commands ###
