"""empty message

Revision ID: ad29cc6bd826
Revises: e1909829d84f
Create Date: 2022-09-16 12:56:15.249543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad29cc6bd826'
down_revision = 'e1909829d84f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email_verified_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email_verified_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
