"""empty message

Revision ID: 46c814dca8b2
Revises: 
Create Date: 2022-09-15 22:07:13.329845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c814dca8b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=80), nullable=True),
    sa.Column('tags', sa.String(length=300), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('industry_type', sa.String(length=80), nullable=True),
    sa.Column('latitude', sa.String(length=80), nullable=True),
    sa.Column('longitude', sa.String(length=80), nullable=True),
    sa.Column('logo', sa.String(length=200), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('cell', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('remember_token', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fleets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('is_booked', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('make', sa.String(length=80), nullable=False),
    sa.Column('year', sa.BigInteger(), nullable=False),
    sa.Column('registration_number', sa.String(length=80), nullable=False),
    sa.Column('date_registered', sa.DateTime(), nullable=False),
    sa.Column('mileage', sa.Float(), nullable=False),
    sa.Column('image', sa.String(length=80), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ondemands',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('is_booked', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('fleet_id', sa.BigInteger(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['fleet_id'], ['fleets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ondemands')
    op.drop_table('fleets')
    op.drop_table('users')
    op.drop_table('companies')
    # ### end Alembic commands ###
